import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/components/NavBar";

import ThemeRegistry from '@/app/providers/ThemeRegistry';
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    let emotionStyles = '';

    try {
      // Only run on server build: create a temporary cache and extract critical CSS
      // Use dynamic require so bundlers don't try to include these in client bundles
      const createCache = require('@emotion/cache').default;
      const createEmotionServer = require('@emotion/server/create-instance').default;
      const cache = createCache({ key: 'mui', prepend: true });
      const { extractCriticalToChunks, constructStyleTagsFromChunks } = createEmotionServer(cache);
      const chunks = extractCriticalToChunks('');
      emotionStyles = constructStyleTagsFromChunks(chunks);
    } catch (e) {
      // ignore in client or if extraction fails
      emotionStyles = '';
    }

    return (
        <html lang="en">
        <head>
          {/* Insert server-side emotion styles */}
          <meta charSet="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ThemeRegistry>
            <NavBar/>
            <main className="py-12">
                {children}
            </main>
            <Footer/>
        </ThemeRegistry>
        </body>
        </html>
    );
}
